# Generated by Django 5.2.4 on 2025-08-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='posts/1.png', upload_to='post'),
        ),
    ]
