openapi: 3.0.3
info:
  title: LOGOUT APIs
  version: "1.0"

paths:
  /api/logout:
    post:
      summary: Logout from the current session/device
      description: |
        Logs out **only the current session/device**.  
        Requires a valid access token (JWT).
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successfully logged out from this session
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Logged out successfully
                  response:
                    type: object
                    properties:
                      userid:
                        type: string
                        example: "261309"
                      session_id:
                        type: string
                        example: "S-01520"
                      revoked_count:
                        type: integer
                        example: 1
        "400":
          description: Missing or invalid parameters
        "500":
          description: Internal server error

  /api/logout_all:
    post:
      summary: Logout from all sessions/devices
      description: |
        Logs out **from all active sessions** for the given `userid`.  
        Requires a valid access token (JWT).
      security:
        - bearerAuth: []
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                userid:
#                  type: string
#                  example: "261309"
#              required:
#                - userid
      responses:
        "200":
          description: Successfully logged out from all sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Logged out from all sessions
                  response:
                    type: object
                    properties:
                      userid:
                        type: string
                        example: "261309"
                      revoked_count:
                        type: integer
                        example: 5
        "400":
          description: Missing or invalid parameters
        "500":
          description: Internal server error

