openapi: 3.0.3
info:
  title: KCL Unified API Documentation
  version: "1.0"
  description: Unified Swagger combining all feature APIs.

servers:
  - url: /
    description: Localhost or ngrok

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  # LOGIN + MPIN (from login.yaml)
  /api/generate_otp:
    $ref: './login.yaml#/paths/~1api~1generate_otp'
  /api/verify_otp:
    $ref: './login.yaml#/paths/~1api~1verify_otp'
  /api/create_mpin:
    $ref: './login.yaml#/paths/~1api~1create_mpin'
  /api/mpin_generate_otp:
    $ref: './login.yaml#/paths/~1api~1mpin_generate_otp'
  /api/verify_mpin:
    $ref: './login.yaml#/paths/~1api~1verify_mpin'
  /api/mpin_verify_otp:
    $ref: './login.yaml#/paths/~1api~1mpin_verify_otp'
  /api/regenerate_mpin:
    $ref: './login.yaml#/paths/~1api~1regenerate_mpin'

  # user details
  /api/user_profile:
    $ref: './user_profile.yaml#/paths/~1api~1user_profile'
  /api/user_handle:
    $ref: './user_profile.yaml#/paths/~1api~1user_handle'
  /api/profile_setup:
    $ref: './user_details.yaml#/paths/~1api~1profile_setup'


  # Pincode
  /api/pincode_verify:
    $ref: './pincode_verify.yaml#/paths/~1api~1pincode_verify'

  # Dashboard
  /api/dashboard_images:
    $ref: './dashboard_api.yaml#/paths/~1api~1dashboard_images'
  /api/dashboard_more_option:
    $ref: './dashboard_api.yaml#/paths/~1api~1dashboard_more_option'

  # Contest
  /api/contest_this_season:
    $ref: './contest.yaml#/paths/~1api~1contest_this_season'

  # Language
  /api/get_languages:
    $ref: './language_api.yaml#/paths/~1api~1get_languages'

  # Authentication
  /api/auth/refresh:
    $ref: './auth.yaml#/paths/~1api~1auth~1refresh'

  # Logout
  /api/logout:
    $ref: './logout.yaml#/paths/~1api~1logout'
  /api/logout_all:
    $ref: './logout.yaml#/paths/~1api~1logout_all'

  # Basic Details Verification
  /api/basic_details_verification:
    $ref: './basic_details_verification.yaml#/paths/~1api~1basic_details_verification'

  # Communication Address
  /api/communication_address:
    $ref: './communication_address.yaml#/paths/~1api~1communication_address'

  # Aadhar verify otp
  /api/aadhar_generate_otp:
    $ref: './aadhar.yaml#/paths/~1api~1aadhar_generate_otp'
  /api/aadhar_verify_otp:
    $ref: './aadhar.yaml#/paths/~1api~1aadhar_verify_otp'
  /api/aadhar_eligibility:
    $ref: './aadhar.yaml#/paths/~1api~1aadhar_eligibility'

    # Edit your profile
  /api/edit_your_profile:
    $ref: './edityourprofile.yaml#/paths/~1api~1edit_your_profile'
  

