openapi: 3.0.3
info:
  title: AADHAR API
  version: "1.0"
paths:
  /api/aadhar_generate_otp:
    post:
      tags:
        - Aadhar
      summary: Generate Aadhar OTP
      description: Generates an OTP for Aadhar verification.
      security:
        - bearerAuth: [ ]
      parameters:
        - in: header
          name: user_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aadhar_number:
                  type: string
              required:
                - aadhar_number
      responses:
        "200":
          description: OTP generated successfully
          content:
            application/json:
              examples:
                success:
                  summary: Successful OTP generation
                  value:
                    statusCode: 200
                    message: "OTP generated successfully."
                    response: { }
        "500":
          description: Internal Server Error
          content:
            application/json:
              examples:
                server_error:
                  summary: Server error
                  value:
                    statusCode: 500
                    message: "Internal server error"
                    response: { }


  /api/aadhar_verify_otp:
    post:
      tags:
        - Aadhar
      summary: Verify Aadhar OTP
      description: Verifies the Aadhar OTP and updates the user details.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aadhar_number:
                  type: string
                aadhar_otp:
                  type: string
              required:
                - aadhar_number
                - aadhar_otp
      parameters:
        - in: header
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Aadhar OTP verified successfully
          content:
            application/json:
              examples:
                example1:
                  summary: Success response
                  value:
                    statusCode: 200
                    message: "aadhar otp verified"
                    response:
                      details:
                        userid: "12345"
                        name: "Test Sample"
                        dob: "20/12/1999"
                        gender: "male"
                        user_type: false
                        isaadharverified: true
                        isCommunicationaddressadded: false
                        communicationaddress:
                          addresslineOne: ""
                          addresslineTwo: ""
                          City: ""
                          State: ""
                          pincode: ""
                          mobilenumber: ""
                        address:
                          addresslineOne: "456, block 10000, building 200000"
                          addresslineTwo: "xyz society,abc area"
                          City: "City 123"
                          State: "State 123"
                          pincode: "2345617"
                          mobilenumber: "98765421901"
                      ismpinsetup: false
                      isprofilesetup: false

        "500":
          description: Internal Server Error
          content:
            application/json:
              examples:
                server_error:
                  summary: Server error
                  value:
                    statusCode: 500
                    message: "Internal server error"
                    response: {}

