# Generated by Django 5.2.4 on 2025-08-20 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='husband',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='relations.husband'),
        ),
    ]
