# Generated by Django 5.2.4 on 2025-08-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_alter_wife_husband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='husband',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relations.husband'),
        ),
    ]
