/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thecodinginterface.avrodomainevents;

import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

public class LibraryTest {

    @Test
    public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "Expected true");
    }
}
